name: Check for lint errors

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
      - uses: auguwu/node-pm-action@v1.0.1
        id: node-cache
      - if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.0
      - uses: auguwu/node-pm-action@v1.0.1
      - run: npm run lint
